# GOVERNANCE
:toc:
:toclevels: 2
:revnumber: 1.1
:revdate: June 7th, 2021
:numbered:
:comments!:
:tip-caption: Example

## Overview

We will govern ourselves through interlinked, semi-autonomous, self-organizing circles. A *circle* is a group of people with an *aim* (a specific purpose) who work together to accomplish that purpose, including making operations and policy decisions by *consent* within their specific *domain* (area of responsibility). Consent is defined as having no argued objections which express a concern that the decision will negatively affect the circles ability to fulfill its aim.

Our governance structure is designed to evolve through regular evaluation so it reflects our living community process.

## Aims of our Governance System

The governance system of our community aims to

* support broad participation by members in both governance and operational work,
* foster a positive sense of community and connections among community members,
* ensure that all voices matter,
* maintain the integrity of circles to make decisions within their area of responsibility and have appropriate community input on those decisions,
* work with concerns during decision making in a constructive way,
* develop leadership and consent-building skills of our members.

## Circle Structure

### Hierarchy of Inter-Linked Circles

In the structure of Circles, a more focused circle is double-linked to the next broader circle by the <<Circle Leader>> and or more <<Delegates>> of the more focused circle.

TIP: The Community Life Circle would affirm the purpose and responsibilities of the Care & Counsel Circle.

### Full Circle

ifdef::comments[NOTE: This needs to be overhauled. ]

Comprised of all community members and associate members.

These decisions are the domain of the Full Circle:

. Significant and permanent changes to the physical community;
. Significant change to the governance structure;
. Significant impact on members in terms of money, housing, and/or liability;
. Changes to Master Deed and its amendments, Bylaws and its amendments, and agreements with the Town of Amherst;
. Annual budget decisions and any mid-term revisions that increase the budget by more than 10%;
. Decisions where the Coordinating Circle cannot achieve consent; and
. Decisions of the Coordinating Circle that have been appealed by three or more individuals, no two from the same household.

Note: non-property owners may not object to budget decisions.

### Coordinating Circle

Comprised of the leaders and delegates of the four main Work Circles.

### Core Work Circles

* Buildings & Grounds (B&G)
* Community Life (CL),
* Common House (CH),
* Plants, Animals, Land Stewards (PALS)

### Subcircles and Helping Circles

Subcircles are Circles that are focused on a particular part of a Main Work Circle’s area of responsibility.

TIP: The Care & Counsel Circle is a Sub-Circle of the Community Life Circle.

Helping Circles research and recommend actions or policies to the Circle that created it. It can also carry out specific, short-term work assignments.

TIP: A Retreat Planning Circle would be a Helping Circle to the Coordinating Circle.

### Expanded Work Circles

Each Work Circle may have one or more Sub-Circles and/or Helping Circles, as well as individuals who do specific tasks but who is not a member of the Work Circle.

TIP: Someone may be the bike room coordinator and connected to the Common House Circle but not participate in that Circle’s meetings.

All the associated groups and individuals connected to a Circle comprise its Expanded Work Circle.

TIP: The B&G Expanded Work Circle includes - in addition to its sub circles - the mowing team, plowing team, the cart coordinator, etc.

Meetings may be called between and among these entities as relevant. The purpose, area of responsibility, and evaluation will be determined specifically for each meeting.

TIP: CH Committee may meet with all the basement coordinators to discuss new ideas for reorganizing that space, and so on.

## Circle Member Roles

With the exception of the Circle leader and the delegate(s) any member may fill more than one role, and roles may be combined.

Any selected role person may appoint a substitute to cover a temporary absence or a substitute may be made by the facilitator, secretary or Circle leader.

### Circle Leader

The Circle leader is selected by their Circle and confirmed by the next broader circle. Their role is to oversee operations of their Circle. The Circle leader is a member of both their Circle and the next broader Circle. The leader may make time-sensitive decisions without being authorized to do so by their Circle; those decisions must be reviewed at the next Circle meeting.

### Facilitator

A facilitator is selected by each circle to conduct circle meetings, provide leadership in decision- making, support listening and mutual understanding, and ensure that the circle is functioning based on the principles and methods of Dynamic Governance. The facilitator role can be rotated among members.

### Secretary

Each circle selects an administrative secretary to manage the affairs of the circle and perform tasks related to its functioning: such as arranging and announcing circle meetings, preparing the agenda in consultation with other Circle members, distributing study materials and proposals, taking minutes or ensuring that minutes are taken, distributing minutes, and performing any other tasks assigned by the Circle. As the keeper of the records, the Secretary interprets policies when questions arise.

### Logbook Keeper

A logbook keeper is selected by the Circle to maintain the circle logbook. Depending on the size of the circle and the complexity of its work, the role of the logbook keeper may be combined with that of the Secretary. See section <<Record-Keeping>>.

### Delegates

Each Circle selects one or more delegates, other than the Circle leader, to participate in the next broader circle. Delegates participate as full members in both circles. A delegate cannot be the same person as the Circle leader.

## Circles Governance

### Aim and Domain of a Circle

Purpose (Aim):: To meet community needs by providing community services within their area of responsibility in ways that are effective, efficient and transparent.

Area of Responsibility (Domain):: Policies, operations, and budget of this Circle. Each establishes or confirms the purpose, area of responsibility and leadership selection of sub-circles. They call for <<Community Conversations>> and conduct other information gathering as needed to inform decisions that need greater input.

### Circle Membership

Core members of a circle are those who carry out the responsibilities of that circle and who regularly attend meetings as set by the circle.

There are other individuals who carry out tasks related to a particular Circle but are not core members of that circle. They are part of their relevant <<Expanded Work Circles>>.

To ensure well-run productive Circles, every Circle will have a defined membership of individuals who agree to follow these best practices:

* attend Circle meetings regularly
* inform the Circle Secretary if you will be absent
* carry out the Circle’s work in between meetings
* make an effort to resolve interpersonal conflicts that occur within the Circle upon request of the Circle

Each Circle can set additional criteria as long as they are clear and transparent and relevant to the Circle’s area of responsibility.

The intention of the circle is to be inclusive and welcoming, balanced with the responsibility to respect and commit to the circle's forward progress. Therefore, new members may be asked to “get up to speed” by talking or working with a member between meetings so as not to slow down the work of the circle.

No one may be denied membership in a Circle or asked to leave a Circle on the basis of personal preferences.

If a member is having difficulty meeting the criteria, the Circle may initiate a respectful and open-minded conversation to understand what is going on for the member. If the member is not able to meet the Circle’s agreements, s/he may be asked to resign from Circle membership.

### Circle Meetings

Circles determine their own meeting frequency.

Non-Circle Members are welcome to attend any Circle's meetings. Non-Circle members can always participate in a meeting's opening and closing go-rounds. Circles will reserve up to 15 minutes near the beginning of a Circle meeting to hear any community concern. The Circle may choose to invite anyone to present or comment on any topic at any time.

### Community Gatherings

There are two types of community gatherings: <<Community Conversations>> and <<Full Circle Meetings>>. One or the other will occur monthly.

#### Community Conversations

Community Conversations can be called by any Circle for the purpose of generating input that will help that Circle make a decision. Community Conversations are focused on exploration, dialogue and understanding and are not decision making meetings. All are welcome to attend and participate in Community Conversations.

#### Full Circle Meetings

All residents and Associates are members of the Full Circle. Full Circle meetings are decision making meetings and will be scheduled by the Coordinating Circle as the need arises. At minimum there will be three Full Circle meetings a year - these include the annual retreat and the annual budget meeting. Other Full Circle meetings may be called by the Coordinating Circle, as needed for a decision that fall into the domain of the Full Circle as determined by the Coordinating Circle.

### Record-Keeping

Each circle will create and maintain a logbook accessible to the full community that includes but is not limited to a) the circle’s purpose, policy decisions and meeting minutes; and b) any other documents that record the Circle’s activities and plans.

### Evaluation

All policy decisions will be in effect for a defined period of time, and be evaluated at or before the end of that period of time. The policy will then be terminated, continued or revised, as appropriate, based on that evaluation.

Minutes produced and posted for community access. Evaluation at conclusion of each meeting. Annual self-evaluation and by broader Circle. Periodic evaluations of specific projects according to their purposes.

TIP: Are we achieving our intention of having 2 meals a week?.

### Ongoing Learning

Each Circle is responsible for the ongoing learning of its members in three areas: communication/interpersonal relationships, governance structure/meeting and work processes and work content (as in finances in a Finance Committee and equipment repair in Buildings & Grounds). The Coordinating Circle is responsible for community-wide skill building and education.

## Decision Making

### General Process

Meetings and decision making will proceed as outlined in the Consent and Meeting Process SummaryGuide (see appendix).

A question comes to a Circle -- it may decide the question, research it, survey community members, or send the question to another Circle for input or decision. A Circle may appoint a Helping Circle to research the question and make a recommendation. A Circle can ask for time in a Community Conversation to generate more input. These Community Conversations will be held monthly (or more or less as needed) with dates predetermined annually. In addition, any individual can give input to any Circle member. Any individual can request to be heard by any Circle that they are not a member of. All Circle meeting minutes will be publicly available.

### The Principle of Consent

Decisions by Circles are made by consent, including selection of people for circle membership roles, except as required by law and/or as otherwise stated in the bylaws.

Consent is the absence of a objection by any member of the circle. Objections are measured against the aim of the circle or the needs of our cohousing community as a whole. Personal preference is not the basis for objection. It is the responsibility of the whole circle -- including the objecting party -- to understand, explore and respond to an objection.

TIP: Valuable tools to understand and explore an objection are

- inviting external experts,
- referring to a helping circle,
- building capacity of the circle to practice DG,
- shorten the time to review,
- dividing the proposal into smaller ones,
- measuring the concern.

TIP: A small group within B&G formed a new proposal about ice removal. The proposal received several objections which led to new information and a fresh perspective. It resulted in an 
improved policy.

TIP: One community goal is to have meals available for everyone twice a week. While some may have a personal preference for having all vegetarian meals, they would not have an objection to meals that include meat unless there was no vegetarian option. To welcome everyone to community meals, we might object to a meal policy that never included meat or a meal policy that did not require a vegetarian option when a meat oriented meal was served.

If a Circle, after considerable effort, cannot achieve consent on a proposal and the proposal still has support, the circle leader can refer the matter to the next broader circle for decision.

TIP: From Membership Circle to Community Life Circle to Coordinating Circle.

### Circuit Breaker

If all options to come to consent have been exhausted and the proposal still has support, a meeting with a quorum of at least 50% of HOA households present can be invoked by the Coordinating Circle. The meeting has to facilitate two votes: 1) to suspend consent and 2) to decide the matter at hand, both requiring affirmation by a 75% supermajority. Quorum and voting are weighted by households according to ownership stake. See Bylaws, Article 5, Section 6.

### Appeal Process

* Any individual may appeal any decision made by any Circle. That appeal will first be heard by the Circle(s) to which the individual belongs. If that Circle agrees with the appeal, they will send selected delegates to the Circle which made the decision. These delegates will temporarily join the Circle that made the original decision for the purpose of confirming, rejecting or amending the decision in question.
* Alternatively, three individuals, no two from the same house, can appeal any decision to the circle that made the decision. To facilitate a timely response and avoid holding up a decision, the following process is recommended:

Those appealing will go to the circle that made the decision, in order to confirm or amend that decision (in one session); if not successful in that session, those with concerns along with circle delegates seek assistance from Care and Counsel to get resolution (within two sessions).

If that is not successful, it moves to the next broader circle.

## Evaluation / Measure

How we will evaluate this Governance Agreement.

* Frequency of Circle Meetings
* Attendance of Circle Members
* Record of Circle Meetings (Minutes)
* Availability of Minutes to all community members
* Summary of policy decisions that have been made in the period
* Survey of Satisfaction with those decisions
* Summary of objections that arose and how they were processed
* Evaluations in each Circle and in the Full Circle - what went well, what could have been improved, suggestions for improvement
* Effectiveness: are decisions getting made, is the community functioning as well or better than before?
* Efficiency: is the speed with which decisions & actions are taken appropriate to the decisions or actions?
* Transparency is there easy community access to information about the decisions made by the Circle?
* Consent decision in a Full Circle: Are there objections to continuing the experiment?
